apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  database_user: {{ .Values.database.user | b64enc | quote }}
  database_password: {{ .Values.database.password | b64enc | quote }}
  database_name: {{ .Values.database.db | b64enc | quote }}
  database_host: {{ .Values.database.host | b64enc | quote }}
  database_url: {{ printf "postgresql://%s:%s@%s:%v/%s?sslmode=require&channel_binding=require" .Values.database.user .Values.database.password .Values.database.host .Values.database.port .Values.database.db | b64enc | quote }}
  better_auth_secret: {{ .Values.auth.secret | b64enc | quote }}
  openai_api_key: {{ .Values.aiAgent.openAIApiKey | b64enc | quote }}
